/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.pojos;


import com.swanpipe.jooq.rx.tables.interfaces.IAccount;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account implements VertxPojo, IAccount {

    private static final long serialVersionUID = 1161054837;

    private Integer id;
    private Boolean enabled;

    public Account() {}

    public Account(IAccount value) {
        this.id = value.getId();
        this.enabled = value.getEnabled();
    }

    public Account(
        Integer id,
        Boolean enabled
    ) {
        this.id = id;
        this.enabled = enabled;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public Account setId(Integer id) {
        this.id = id;
        return this;
    }

    @Override
    public Boolean getEnabled() {
        return this.enabled;
    }

    @Override
    public Account setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Account (");

        sb.append(id);
        sb.append(", ").append(enabled);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IAccount from) {
        setId(from.getId());
        setEnabled(from.getEnabled());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IAccount> E into(E into) {
        into.from(this);
        return into;
    }

    public Account(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
