/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.daos;


import com.swanpipe.jooq.rx.tables.Account;
import com.swanpipe.jooq.rx.tables.records.AccountRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.reactivepg.ReactiveRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountDao extends AbstractReactiveVertxDAO<AccountRecord, com.swanpipe.jooq.rx.tables.pojos.Account, Integer, Single<List<com.swanpipe.jooq.rx.tables.pojos.Account>>, Single<Optional<com.swanpipe.jooq.rx.tables.pojos.Account>>, Single<Integer>, Single<Integer>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<AccountRecord,com.swanpipe.jooq.rx.tables.pojos.Account,Integer> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public AccountDao(Configuration configuration, io.reactiverse.reactivex.pgclient.PgClient delegate) {
        super(Account.ACCOUNT, com.swanpipe.jooq.rx.tables.pojos.Account.class, new ReactiveRXQueryExecutor<AccountRecord,com.swanpipe.jooq.rx.tables.pojos.Account,Integer>(configuration,delegate,com.swanpipe.jooq.rx.tables.mappers.RowMappers.getAccountMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.swanpipe.jooq.rx.tables.pojos.Account object) {
        return object.getId();
    }

    /**
     * Find records that have <code>enabled IN (values)</code> asynchronously
     */
    public Single<List<com.swanpipe.jooq.rx.tables.pojos.Account>> findManyByEnabled(List<Boolean> values) {
        return findManyByCondition(Account.ACCOUNT.ENABLED.in(values));
    }

    @Override
    public ReactiveRXQueryExecutor<AccountRecord,com.swanpipe.jooq.rx.tables.pojos.Account,Integer> queryExecutor(){
        return (ReactiveRXQueryExecutor<AccountRecord,com.swanpipe.jooq.rx.tables.pojos.Account,Integer>) super.queryExecutor();
    }
}
