/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.daos;


import com.swanpipe.jooq.rx.tables.Persona;
import com.swanpipe.jooq.rx.tables.records.PersonaRecord;

import io.github.jklingsporn.vertx.jooq.shared.reactive.AbstractReactiveVertxDAO;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;


import io.reactivex.Single;
import java.util.Optional;
import io.github.jklingsporn.vertx.jooq.rx.reactivepg.ReactiveRXQueryExecutor;
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonaDao extends AbstractReactiveVertxDAO<PersonaRecord, com.swanpipe.jooq.rx.tables.pojos.Persona, String, Single<List<com.swanpipe.jooq.rx.tables.pojos.Persona>>, Single<Optional<com.swanpipe.jooq.rx.tables.pojos.Persona>>, Single<Integer>, Single<String>> implements io.github.jklingsporn.vertx.jooq.rx.VertxDAO<PersonaRecord,com.swanpipe.jooq.rx.tables.pojos.Persona,String> {

    /**
     * @param configuration The Configuration used for rendering and query execution.
     * @param vertx the vertx instance
     */
    public PersonaDao(Configuration configuration, io.reactiverse.reactivex.pgclient.PgClient delegate) {
        super(Persona.PERSONA, com.swanpipe.jooq.rx.tables.pojos.Persona.class, new ReactiveRXQueryExecutor<PersonaRecord,com.swanpipe.jooq.rx.tables.pojos.Persona,String>(configuration,delegate,com.swanpipe.jooq.rx.tables.mappers.RowMappers.getPersonaMapper()));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.swanpipe.jooq.rx.tables.pojos.Persona object) {
        return object.getId();
    }

    /**
     * Find records that have <code>account_id IN (values)</code> asynchronously
     */
    public Single<List<com.swanpipe.jooq.rx.tables.pojos.Persona>> findManyByAccountId(List<Integer> values) {
        return findManyByCondition(Persona.PERSONA.ACCOUNT_ID.in(values));
    }

    /**
     * Find records that have <code>display_name IN (values)</code> asynchronously
     */
    public Single<List<com.swanpipe.jooq.rx.tables.pojos.Persona>> findManyByDisplayName(List<String> values) {
        return findManyByCondition(Persona.PERSONA.DISPLAY_NAME.in(values));
    }

    /**
     * Find records that have <code>created IN (values)</code> asynchronously
     */
    public Single<List<com.swanpipe.jooq.rx.tables.pojos.Persona>> findManyByCreated(List<Timestamp> values) {
        return findManyByCondition(Persona.PERSONA.CREATED.in(values));
    }

    @Override
    public ReactiveRXQueryExecutor<PersonaRecord,com.swanpipe.jooq.rx.tables.pojos.Persona,String> queryExecutor(){
        return (ReactiveRXQueryExecutor<PersonaRecord,com.swanpipe.jooq.rx.tables.pojos.Persona,String>) super.queryExecutor();
    }
}
