/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ILogin extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.login.id</code>.
     */
    public ILogin setId(String value);

    /**
     * Getter for <code>public.login.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.login.account_id</code>.
     */
    public ILogin setAccountId(Integer value);

    /**
     * Getter for <code>public.login.account_id</code>.
     */
    public Integer getAccountId();

    /**
     * Setter for <code>public.login.password</code>.
     */
    public ILogin setPassword(String value);

    /**
     * Getter for <code>public.login.password</code>.
     */
    public String getPassword();

    /**
     * Setter for <code>public.login.enabled</code>.
     */
    public ILogin setEnabled(Boolean value);

    /**
     * Getter for <code>public.login.enabled</code>.
     */
    public Boolean getEnabled();

    /**
     * Setter for <code>public.login.created</code>.
     */
    public ILogin setCreated(Timestamp value);

    /**
     * Getter for <code>public.login.created</code>.
     */
    public Timestamp getCreated();

    /**
     * Setter for <code>public.login.last_successful_login</code>.
     */
    public ILogin setLastSuccessfulLogin(Timestamp value);

    /**
     * Getter for <code>public.login.last_successful_login</code>.
     */
    public Timestamp getLastSuccessfulLogin();

    /**
     * Setter for <code>public.login.last_failed_login</code>.
     */
    public ILogin setLastFailedLogin(Timestamp value);

    /**
     * Getter for <code>public.login.last_failed_login</code>.
     */
    public Timestamp getLastFailedLogin();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ILogin
     */
    public void from(com.swanpipe.jooq.rx.tables.interfaces.ILogin from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ILogin
     */
    public <E extends com.swanpipe.jooq.rx.tables.interfaces.ILogin> E into(E into);

    @Override
    public default ILogin fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getString("id"));
        setAccountId(json.getInteger("account_id"));
        setPassword(json.getString("password"));
        setEnabled(json.getBoolean("enabled"));
        setCreated(Timestamp.from(OffsetDateTime.parse(json.getString("created")).toInstant()));
        setLastSuccessfulLogin(Timestamp.from(OffsetDateTime.parse(json.getString("last_successful_login")).toInstant()));
        setLastFailedLogin(Timestamp.from(OffsetDateTime.parse(json.getString("last_failed_login")).toInstant()));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("account_id",getAccountId());
        json.put("password",getPassword());
        json.put("enabled",getEnabled());
        json.put("created",OffsetDateTime.ofInstant(getCreated().toInstant(), ZoneOffset.UTC));
        json.put("last_successful_login",OffsetDateTime.ofInstant(getLastSuccessfulLogin().toInstant(), ZoneOffset.UTC));
        json.put("last_failed_login",OffsetDateTime.ofInstant(getLastFailedLogin().toInstant(), ZoneOffset.UTC));
        return json;
    }

}
