/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.interfaces;


import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IPersona extends VertxPojo, Serializable {

    /**
     * Setter for <code>public.persona.id</code>.
     */
    public IPersona setId(String value);

    /**
     * Getter for <code>public.persona.id</code>.
     */
    public String getId();

    /**
     * Setter for <code>public.persona.account_id</code>.
     */
    public IPersona setAccountId(Integer value);

    /**
     * Getter for <code>public.persona.account_id</code>.
     */
    public Integer getAccountId();

    /**
     * Setter for <code>public.persona.display_name</code>.
     */
    public IPersona setDisplayName(String value);

    /**
     * Getter for <code>public.persona.display_name</code>.
     */
    public String getDisplayName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IPersona
     */
    public void from(com.swanpipe.jooq.rx.tables.interfaces.IPersona from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IPersona
     */
    public <E extends com.swanpipe.jooq.rx.tables.interfaces.IPersona> E into(E into);

    @Override
    public default IPersona fromJson(io.vertx.core.json.JsonObject json) {
        setId(json.getString("id"));
        setAccountId(json.getInteger("account_id"));
        setDisplayName(json.getString("display_name"));
        return this;
    }


    @Override
    public default io.vertx.core.json.JsonObject toJson() {
        io.vertx.core.json.JsonObject json = new io.vertx.core.json.JsonObject();
        json.put("id",getId());
        json.put("account_id",getAccountId());
        json.put("display_name",getDisplayName());
        return json;
    }

}
