/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx.tables.records;


import com.swanpipe.jooq.rx.tables.Login;
import com.swanpipe.jooq.rx.tables.interfaces.ILogin;

import io.github.jklingsporn.vertx.jooq.shared.internal.VertxPojo;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LoginRecord extends UpdatableRecordImpl<LoginRecord> implements VertxPojo, Record6<String, Integer, String, Boolean, Timestamp, Timestamp>, ILogin {

    private static final long serialVersionUID = 630726124;

    /**
     * Setter for <code>public.login.id</code>.
     */
    @Override
    public LoginRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.login.id</code>.
     */
    @Override
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.login.account_id</code>.
     */
    @Override
    public LoginRecord setAccountId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.login.account_id</code>.
     */
    @Override
    public Integer getAccountId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.login.password</code>.
     */
    @Override
    public LoginRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.login.password</code>.
     */
    @Override
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.login.enabled</code>.
     */
    @Override
    public LoginRecord setEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.login.enabled</code>.
     */
    @Override
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.login.last_successful_login</code>.
     */
    @Override
    public LoginRecord setLastSuccessfulLogin(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.login.last_successful_login</code>.
     */
    @Override
    public Timestamp getLastSuccessfulLogin() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.login.last_failed_login</code>.
     */
    @Override
    public LoginRecord setLastFailedLogin(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.login.last_failed_login</code>.
     */
    @Override
    public Timestamp getLastFailedLogin() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, String, Boolean, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, String, Boolean, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Login.LOGIN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Login.LOGIN.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Login.LOGIN.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Login.LOGIN.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Login.LOGIN.LAST_SUCCESSFUL_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Login.LOGIN.LAST_FAILED_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastSuccessfulLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getLastFailedLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastSuccessfulLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getLastFailedLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value2(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value4(Boolean value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value5(Timestamp value) {
        setLastSuccessfulLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord value6(Timestamp value) {
        setLastFailedLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LoginRecord values(String value1, Integer value2, String value3, Boolean value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(ILogin from) {
        setId(from.getId());
        setAccountId(from.getAccountId());
        setPassword(from.getPassword());
        setEnabled(from.getEnabled());
        setLastSuccessfulLogin(from.getLastSuccessfulLogin());
        setLastFailedLogin(from.getLastFailedLogin());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends ILogin> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoginRecord
     */
    public LoginRecord() {
        super(Login.LOGIN);
    }

    /**
     * Create a detached, initialised LoginRecord
     */
    public LoginRecord(String id, Integer accountId, String password, Boolean enabled, Timestamp lastSuccessfulLogin, Timestamp lastFailedLogin) {
        super(Login.LOGIN);

        set(0, id);
        set(1, accountId);
        set(2, password);
        set(3, enabled);
        set(4, lastSuccessfulLogin);
        set(5, lastFailedLogin);
    }

    public LoginRecord(io.vertx.core.json.JsonObject json) {
        this();
        fromJson(json);
    }
}
