/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx;


import com.swanpipe.jooq.rx.tables.Account;
import com.swanpipe.jooq.rx.tables.FlywaySchemaHistory;
import com.swanpipe.jooq.rx.tables.Login;
import com.swanpipe.jooq.rx.tables.Persona;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNT_PKEY = Indexes0.ACCOUNT_PKEY;
    public static final Index FLYWAY_SCHEMA_HISTORY_PK = Indexes0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
    public static final Index LOGIN_PKEY = Indexes0.LOGIN_PKEY;
    public static final Index PERSONA_PKEY = Indexes0.PERSONA_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNT_PKEY = Internal.createIndex("account_pkey", Account.ACCOUNT, new OrderField[] { Account.ACCOUNT.ID }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_PK = Internal.createIndex("flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
        public static Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex("flyway_schema_history_s_idx", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
        public static Index LOGIN_PKEY = Internal.createIndex("login_pkey", Login.LOGIN, new OrderField[] { Login.LOGIN.ID }, true);
        public static Index PERSONA_PKEY = Internal.createIndex("persona_pkey", Persona.PERSONA, new OrderField[] { Persona.PERSONA.ID }, true);
    }
}
