/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx;


import com.swanpipe.jooq.rx.tables.Account;
import com.swanpipe.jooq.rx.tables.FlywaySchemaHistory;
import com.swanpipe.jooq.rx.tables.Login;
import com.swanpipe.jooq.rx.tables.Persona;
import com.swanpipe.jooq.rx.tables.records.AccountRecord;
import com.swanpipe.jooq.rx.tables.records.FlywaySchemaHistoryRecord;
import com.swanpipe.jooq.rx.tables.records.LoginRecord;
import com.swanpipe.jooq.rx.tables.records.PersonaRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Identities0.IDENTITY_ACCOUNT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = UniqueKeys0.ACCOUNT_PKEY;
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
    public static final UniqueKey<LoginRecord> LOGIN_PKEY = UniqueKeys0.LOGIN_PKEY;
    public static final UniqueKey<PersonaRecord> PERSONA_PKEY = UniqueKeys0.PERSONA_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LoginRecord, AccountRecord> LOGIN__LOGIN_ACCOUNT_ID_FKEY = ForeignKeys0.LOGIN__LOGIN_ACCOUNT_ID_FKEY;
    public static final ForeignKey<PersonaRecord, AccountRecord> PERSONA__PERSONA_ACCOUNT_ID_FKEY = ForeignKeys0.PERSONA__PERSONA_ACCOUNT_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountRecord, Integer> IDENTITY_ACCOUNT = Internal.createIdentity(Account.ACCOUNT, Account.ACCOUNT.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountRecord> ACCOUNT_PKEY = Internal.createUniqueKey(Account.ACCOUNT, "account_pkey", Account.ACCOUNT.ID);
        public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, "flyway_schema_history_pk", FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK);
        public static final UniqueKey<LoginRecord> LOGIN_PKEY = Internal.createUniqueKey(Login.LOGIN, "login_pkey", Login.LOGIN.ID);
        public static final UniqueKey<PersonaRecord> PERSONA_PKEY = Internal.createUniqueKey(Persona.PERSONA, "persona_pkey", Persona.PERSONA.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<LoginRecord, AccountRecord> LOGIN__LOGIN_ACCOUNT_ID_FKEY = Internal.createForeignKey(com.swanpipe.jooq.rx.Keys.ACCOUNT_PKEY, Login.LOGIN, "login__login_account_id_fkey", Login.LOGIN.ACCOUNT_ID);
        public static final ForeignKey<PersonaRecord, AccountRecord> PERSONA__PERSONA_ACCOUNT_ID_FKEY = Internal.createForeignKey(com.swanpipe.jooq.rx.Keys.ACCOUNT_PKEY, Persona.PERSONA, "persona__persona_account_id_fkey", Persona.PERSONA.ACCOUNT_ID);
    }
}
