/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx;


import com.swanpipe.jooq.rx.tables.Account;
import com.swanpipe.jooq.rx.tables.FlywaySchemaHistory;
import com.swanpipe.jooq.rx.tables.Login;
import com.swanpipe.jooq.rx.tables.Persona;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -804881037;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT = com.swanpipe.jooq.rx.tables.Account.ACCOUNT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.swanpipe.jooq.rx.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.login</code>.
     */
    public final Login LOGIN = com.swanpipe.jooq.rx.tables.Login.LOGIN;

    /**
     * The table <code>public.persona</code>.
     */
    public final Persona PERSONA = com.swanpipe.jooq.rx.tables.Persona.PERSONA;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACCOUNT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Login.LOGIN,
            Persona.PERSONA);
    }
}
