/*
 * This file is generated by jOOQ.
 */
package com.swanpipe.jooq.rx;


import com.swanpipe.jooq.rx.tables.Account;
import com.swanpipe.jooq.rx.tables.FlywaySchemaHistory;
import com.swanpipe.jooq.rx.tables.Login;
import com.swanpipe.jooq.rx.tables.Persona;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = com.swanpipe.jooq.rx.tables.Account.ACCOUNT;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.swanpipe.jooq.rx.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.login</code>.
     */
    public static final Login LOGIN = com.swanpipe.jooq.rx.tables.Login.LOGIN;

    /**
     * The table <code>public.persona</code>.
     */
    public static final Persona PERSONA = com.swanpipe.jooq.rx.tables.Persona.PERSONA;
}
